### ISSUE TITLE
RunKit doesn't like use of 'window'

### ISSUE THREAD

**Issue by tomjon** [jcgertig/date-input-polyfill#10]
When I tried using the RunKit link, https://runkit.com/npm/date-input-polyfill, I got:

`ReferenceError Stack Trace Viewer 
ReferenceError: window is not defined
Fix: Use global instead of window.
RunKit is a node environment, so window and other browser features won’t exist. If you’re just trying to access the global object, you can simply use global instead.`

Presumably you need to use 'window' for this to work in browsers, but it did mean I couldn't test the polyfill in my version of IE11.

**Comment by jcgertig** [comment]
im using this in production and support ie11
