### ISSUE TITLE
Use "data-" prefix for "date-format" attribute name

### ISSUE THREAD

**Issue by toddwelstein** [jcgertig/date-input-polyfill#14]
React doesn't like the attribute "date-format"; it results in an unknown-prop warning and doesn't get rendered to the DOM. Their documentation states, "If you are trying to attach custom data to a standard DOM element, consider using a custom data attribute..."
(https://facebook.github.io/react/warnings/unknown-prop.html)

Here is a pull request with the attribute modified to "data-date-format":
https://github.com/jcgertig/date-input-polyfill/pull/13

**Comment by jcgertig** [comment]
Fixed and published
